export type Macro = { calories: number; protein: number; carbs: number; fat: number };
export type Restaurant = {
  id: string; name: string; short: string; color: string; category: string;
  description: string; accent: string; tags: string[]; logo: string; logoUrl: string;
};
export type MenuItem = Macro & {
  id: string; restaurantId: string; name: string; category: string; serving: string;
  description: string; badges: string[]; control?: "portion" | "quantity" | "size";
};

export const restaurants: Restaurant[] = [
  { id: "panda", name: "Panda Express", short: "P", logo: "Panda", logoUrl: "https://logo.clearbit.com/pandaexpress.com", color: "#e31d3b", accent: "#fff0f1", category: "Asian", description: "Wok-fired favorites", tags: ["Popular", "High Protein"] },
  { id: "chipotle", name: "Chipotle", short: "C", logo: "Chipotle", logoUrl: "https://logo.clearbit.com/chipotle.com", color: "#7a2a1c", accent: "#fff2ec", category: "Mexican", description: "Build-your-own bowls", tags: ["Customizable"] },
  { id: "chickfila", name: "Chick-fil-A", short: "CFA", logo: "Chick-fil-A", logoUrl: "https://logo.clearbit.com/chick-fil-a.com", color: "#db1538", accent: "#fff1f4", category: "Chicken", description: "Chicken & breakfast", tags: ["Trending"] },
  { id: "potbelly", name: "Potbelly", short: "P", logo: "Potbelly", logoUrl: "https://logo.clearbit.com/potbelly.com", color: "#f2a900", accent: "#fff8de", category: "Sandwiches", description: "Toasty sandwiches", tags: ["Sandwiches"] },
  { id: "jimmyjohns", name: "Jimmy John's", short: "JJ", logo: "Jimmy John's", logoUrl: "https://logo.clearbit.com/jimmyjohns.com", color: "#111111", accent: "#f1f1f1", category: "Sandwiches", description: "Freaky fresh favorites", tags: ["Fast"] },
  { id: "jerseymikes", name: "Jersey Mike's", short: "JM", logo: "Jersey Mike's", logoUrl: "https://logo.clearbit.com/jerseymikes.com", color: "#00539b", accent: "#edf6ff", category: "Sandwiches", description: "Fresh sliced subs", tags: ["Sandwiches", "New"] },
  { id: "mcdonalds", name: "McDonald's", short: "M", logo: "McDonald's", logoUrl: "https://logo.clearbit.com/mcdonalds.com", color: "#ffbc0d", accent: "#fff7dd", category: "Burgers", description: "Burgers, fries & breakfast", tags: ["Popular", "New"] },
  { id: "culvers", name: "Culver's", short: "C", logo: "Culver's", logoUrl: "https://logo.clearbit.com/culvers.com", color: "#005ca9", accent: "#eaf5ff", category: "American", description: "ButterBurgers & more", tags: ["American"] },
  { id: "starbucks", name: "Starbucks", short: "S", logo: "Starbucks", logoUrl: "https://logo.clearbit.com/starbucks.com", color: "#00754a", accent: "#e6f7f0", category: "Coffee", description: "Coffee & cafe bites", tags: ["Coffee"] },
  { id: "tacobell", name: "Taco Bell", short: "TB", logo: "Taco Bell", logoUrl: "https://logo.clearbit.com/tacobell.com", color: "#702082", accent: "#f8edff", category: "Mexican", description: "Craveable classics", tags: ["Value"] },
];

export const menuItems: MenuItem[] = [
  { id:"white-rice",restaurantId:"panda",name:"White Steamed Rice",category:"Sides",serving:"1 side · 11 oz",calories:520,protein:10,carbs:118,fat:0,description:"Fluffy steamed white rice",badges:["High Carb"] },
  { id:"teriyaki",restaurantId:"panda",name:"Grilled Teriyaki Chicken",category:"Entrees",serving:"1 entree · 6 oz",calories:275,protein:33,carbs:14,fat:10,description:"Grilled chicken with sweet teriyaki glaze",badges:["High Protein"] },
  { id:"super-greens",restaurantId:"panda",name:"Super Greens",category:"Sides",serving:"1 side · 10 oz",calories:130,protein:9,carbs:14,fat:4,description:"Broccoli, kale and cabbage",badges:["High Volume","Low Calorie"] },
  { id:"orange-chicken",restaurantId:"panda",name:"The Original Orange Chicken",category:"Entrees",serving:"1 entree · 5.92 oz",calories:510,protein:16,carbs:53,fat:24,description:"Crispy chicken wok-tossed in a sweet sauce",badges:["Popular"] },
  { id:"broccoli-beef",restaurantId:"panda",name:"Broccoli Beef",category:"Entrees",serving:"1 entree · 5.44 oz",calories:150,protein:15,carbs:12,fat:6,description:"Tender beef and fresh broccoli",badges:["Low Calorie"] },
  { id:"kung-pao",restaurantId:"panda",name:"Kung Pao Chicken",category:"Entrees",serving:"1 entree · 6.73 oz",calories:320,protein:17,carbs:15,fat:21,description:"Chicken, vegetables and peanuts",badges:["Low Carb"] },
  { id:"chow-mein",restaurantId:"panda",name:"Chow Mein",category:"Sides",serving:"1 side · 11 oz",calories:600,protein:15,carbs:94,fat:23,description:"Stir-fried wheat noodles and vegetables",badges:["Popular"] },
  { id:"spring-roll",restaurantId:"panda",name:"Vegetable Spring Roll",category:"Appetizers",serving:"2 rolls · 3.5 oz",calories:240,protein:4,carbs:24,fat:14,description:"Crispy vegetable-filled rolls",badges:["Vegetarian"] },
  { id:"coke",restaurantId:"panda",name:"Coca-Cola",category:"Drinks",serving:"Medium · 30 fl oz",calories:370,protein:0,carbs:100,fat:0,description:"Ice-cold fountain drink",badges:[] },
  { id:"fortune",restaurantId:"panda",name:"Fortune Cookie",category:"Desserts",serving:"1 cookie",calories:20,protein:0,carbs:5,fat:0,description:"A sweet, crisp finish",badges:["Low Calorie"] },
  { id:"chip-tortilla",restaurantId:"chipotle",name:"Flour Tortilla",category:"Meal Base",serving:"1 burrito tortilla",calories:320,protein:8,carbs:50,fat:9,description:"Soft flour tortilla",badges:[] },
  { id:"chip-taco-shells",restaurantId:"chipotle",name:"Crispy Taco Shells",category:"Meal Base",serving:"3 shells",calories:200,protein:3,carbs:35,fat:6,description:"Three crispy corn taco shells",badges:[] },
  { id:"chip-chicken",restaurantId:"chipotle",name:"Chicken",category:"Protein",serving:"1 scoop · 4 oz",calories:180,protein:32,carbs:0,fat:7,description:"Grilled adobo chicken",badges:["High Protein","Low Carb"] },
  { id:"chip-honey-chicken",restaurantId:"chipotle",name:"Chipotle Honey Chicken",category:"Protein",serving:"1 scoop · 4 oz",calories:210,protein:21,carbs:13,fat:8,description:"Limited-time chicken with a touch of heat and sweet",badges:["High Protein","Limited Time"] },
  { id:"chip-steak",restaurantId:"chipotle",name:"Steak",category:"Protein",serving:"1 scoop · 4 oz",calories:150,protein:21,carbs:1,fat:6,description:"Grilled steak with a smoky finish",badges:["High Protein","Low Carb"] },
  { id:"chip-barbacoa",restaurantId:"chipotle",name:"Barbacoa",category:"Protein",serving:"1 scoop · 4 oz",calories:170,protein:24,carbs:2,fat:7,description:"Slow-braised shredded beef",badges:["High Protein"] },
  { id:"chip-sofritas",restaurantId:"chipotle",name:"Sofritas",category:"Protein",serving:"1 scoop · 4 oz",calories:150,protein:8,carbs:9,fat:10,description:"Braised organic tofu with spices",badges:["Vegetarian"] },
  { id:"chip-white-rice",restaurantId:"chipotle",name:"Cilantro-Lime White Rice",category:"Rice",serving:"1 scoop · 4 oz",calories:210,protein:4,carbs:40,fat:4,description:"Fresh rice with citrus and cilantro",badges:["High Carb"] },
  { id:"chip-brown-rice",restaurantId:"chipotle",name:"Cilantro-Lime Brown Rice",category:"Rice",serving:"1 scoop · 4 oz",calories:210,protein:4,carbs:36,fat:6,description:"Whole-grain rice with citrus and cilantro",badges:["High Carb"] },
  { id:"chip-black-beans",restaurantId:"chipotle",name:"Black Beans",category:"Beans",serving:"1 scoop · 4 oz",calories:130,protein:8,carbs:22,fat:1,description:"Seasoned black beans",badges:["High Volume"] },
  { id:"chip-pinto-beans",restaurantId:"chipotle",name:"Pinto Beans",category:"Beans",serving:"1 scoop · 4 oz",calories:130,protein:8,carbs:21,fat:1,description:"Seasoned pinto beans",badges:["High Volume"] },
  { id:"chip-fajita",restaurantId:"chipotle",name:"Fajita Veggies",category:"Toppings",serving:"1 scoop",calories:20,protein:1,carbs:5,fat:0,description:"Sauteed peppers and onions",badges:["Low Calorie","High Volume"] },
  { id:"chip-corn",restaurantId:"chipotle",name:"Roasted Chili-Corn Salsa",category:"Toppings",serving:"1 scoop",calories:80,protein:3,carbs:16,fat:1,description:"Sweet corn salsa with mild heat",badges:[] },
  { id:"chip-tomato",restaurantId:"chipotle",name:"Fresh Tomato Salsa",category:"Toppings",serving:"1 scoop",calories:25,protein:0,carbs:4,fat:0,description:"Fresh tomato, onion and cilantro",badges:["Low Calorie"] },
  { id:"chip-cheese",restaurantId:"chipotle",name:"Cheese",category:"Toppings",serving:"1 serving",calories:110,protein:6,carbs:1,fat:8,description:"Shredded Monterey Jack cheese",badges:["Low Carb"] },
  { id:"chip-sour-cream",restaurantId:"chipotle",name:"Sour Cream",category:"Toppings",serving:"1 serving",calories:110,protein:2,carbs:2,fat:9,description:"Creamy cultured sour cream",badges:["Low Carb"] },
  { id:"chip-guac",restaurantId:"chipotle",name:"Guacamole",category:"Toppings",serving:"1 serving",calories:230,protein:2,carbs:8,fat:22,description:"Hand-mashed avocado with lime",badges:[] },
  { id:"chip-lettuce",restaurantId:"chipotle",name:"Romaine Lettuce",category:"Toppings",serving:"1 serving",calories:5,protein:0,carbs:1,fat:0,description:"Crisp chopped romaine",badges:["Low Calorie","High Volume"] },
  { id:"chip-side-chicken",restaurantId:"chipotle",name:"Side of Chicken",category:"Protein Cups",serving:"1 side cup · 4 oz",calories:180,protein:32,carbs:0,fat:7,description:"Protein side cup of grilled chicken",badges:["High Protein","Low Carb"] },
  { id:"chip-side-steak",restaurantId:"chipotle",name:"Side of Steak",category:"Protein Cups",serving:"1 side cup · 4 oz",calories:150,protein:21,carbs:1,fat:6,description:"Protein side cup of grilled steak",badges:["High Protein","Low Carb"] },
  { id:"chip-side-barbacoa",restaurantId:"chipotle",name:"Side of Barbacoa",category:"Protein Cups",serving:"1 side cup · 4 oz",calories:170,protein:24,carbs:2,fat:7,description:"Protein side cup of barbacoa",badges:["High Protein"] },
  { id:"chip-side-sofritas",restaurantId:"chipotle",name:"Side of Sofritas",category:"Protein Cups",serving:"1 side cup · 4 oz",calories:150,protein:8,carbs:9,fat:10,description:"Protein side cup of sofritas",badges:["Vegetarian"] },
  { id:"chip-chips",restaurantId:"chipotle",name:"Chips",category:"Sides",serving:"1 regular bag",calories:540,protein:7,carbs:73,fat:25,description:"Regular tortilla chips",badges:[] },
  { id:"chip-side-tortilla",restaurantId:"chipotle",name:"Tortilla on the Side",category:"Sides",serving:"1 flour tortilla",calories:320,protein:8,carbs:50,fat:9,description:"Large flour tortilla served on the side",badges:["High Carb"] },
  { id:"chip-kids-taco-tortillas",restaurantId:"chipotle",name:"Kid's Soft Taco Tortillas",category:"Kids Base",serving:"2 tortillas",calories:170,protein:5,carbs:27,fat:5,description:"Two kid-size soft flour tortillas",badges:["Kids"] },
  { id:"chip-kids-quesadilla-tortilla",restaurantId:"chipotle",name:"Kid's Quesadilla Tortilla",category:"Kids Base",serving:"1 tortilla",calories:80,protein:2,carbs:13,fat:2.5,description:"Small flour tortilla for kids quesadilla",badges:["Kids"] },
  { id:"chip-kids-crispy-shells",restaurantId:"chipotle",name:"Kid's Crispy Corn Tortillas",category:"Kids Base",serving:"2 shells",calories:130,protein:2,carbs:19,fat:6,description:"Two crispy corn taco shells",badges:["Kids"] },
  { id:"chip-kids-chicken",restaurantId:"chipotle",name:"Kid's Chicken",category:"Kids Proteins",serving:"2 oz",calories:90,protein:15,carbs:0,fat:3,description:"Kid-sized grilled chicken portion",badges:["Kids","High Protein"] },
  { id:"chip-kids-steak",restaurantId:"chipotle",name:"Kid's Steak",category:"Kids Proteins",serving:"2 oz",calories:70,protein:10,carbs:1,fat:3,description:"Kid-sized steak portion",badges:["Kids","High Protein"] },
  { id:"chip-kids-barbacoa",restaurantId:"chipotle",name:"Kid's Barbacoa",category:"Kids Proteins",serving:"2 oz",calories:80,protein:12,carbs:1,fat:3,description:"Kid-sized barbacoa portion",badges:["Kids","High Protein"] },
  { id:"chip-kids-sofritas",restaurantId:"chipotle",name:"Kid's Sofritas",category:"Kids Proteins",serving:"2 oz",calories:70,protein:4,carbs:5,fat:5,description:"Kid-sized sofritas portion",badges:["Kids","Vegetarian"] },
  { id:"chip-kids-white-rice",restaurantId:"chipotle",name:"Kid's Cilantro-Lime White Rice",category:"Kids Rice & Beans",serving:"2 oz",calories:100,protein:2,carbs:20,fat:2,description:"Kid-sized white rice portion",badges:["Kids"] },
  { id:"chip-kids-brown-rice",restaurantId:"chipotle",name:"Kid's Cilantro-Lime Brown Rice",category:"Kids Rice & Beans",serving:"2 oz",calories:110,protein:2,carbs:18,fat:3,description:"Kid-sized brown rice portion",badges:["Kids"] },
  { id:"chip-kids-black-beans",restaurantId:"chipotle",name:"Kid's Black Beans",category:"Kids Rice & Beans",serving:"3 oz",calories:100,protein:6,carbs:16,fat:1,description:"Kid-sized black beans portion",badges:["Kids"] },
  { id:"chip-kids-pinto-beans",restaurantId:"chipotle",name:"Kid's Pinto Beans",category:"Kids Rice & Beans",serving:"3 oz",calories:100,protein:6,carbs:15,fat:1,description:"Kid-sized pinto beans portion",badges:["Kids"] },
  { id:"chip-kids-fajita",restaurantId:"chipotle",name:"Kid's Fajita Vegetables",category:"Kids Toppings",serving:"2 oz",calories:20,protein:1,carbs:5,fat:0,description:"Kid-sized fajita vegetable portion",badges:["Kids","Low Calorie"] },
  { id:"chip-kids-tomato",restaurantId:"chipotle",name:"Kid's Fresh Tomato Salsa",category:"Kids Toppings",serving:"2 oz",calories:15,protein:0,carbs:1,fat:0,description:"Kid-sized fresh tomato salsa",badges:["Kids","Low Calorie"] },
  { id:"chip-kids-corn",restaurantId:"chipotle",name:"Kid's Roasted Chili-Corn Salsa",category:"Kids Toppings",serving:"2 oz",calories:40,protein:1,carbs:9,fat:1,description:"Kid-sized corn salsa",badges:["Kids"] },
  { id:"chip-kids-cheese",restaurantId:"chipotle",name:"Kid's Cheese",category:"Kids Toppings",serving:"1 oz",calories:110,protein:6,carbs:1,fat:8,description:"Kid-sized cheese portion",badges:["Kids"] },
  { id:"chip-kids-sour-cream",restaurantId:"chipotle",name:"Kid's Sour Cream",category:"Kids Toppings",serving:"1 oz",calories:60,protein:1,carbs:1,fat:5,description:"Kid-sized sour cream portion",badges:["Kids"] },
  { id:"chip-kids-guac",restaurantId:"chipotle",name:"Kid's Guacamole",category:"Kids Toppings",serving:"2 oz",calories:110,protein:1,carbs:3,fat:11,description:"Kid-sized guacamole portion",badges:["Kids"] },
  { id:"chip-kids-romaine",restaurantId:"chipotle",name:"Kid's Romaine Lettuce",category:"Kids Toppings",serving:"1 oz",calories:5,protein:0,carbs:1,fat:0,description:"Kid-sized romaine lettuce",badges:["Kids","Low Calorie"] },
  { id:"chip-kids-chips",restaurantId:"chipotle",name:"Kid's Chips",category:"Kids Fruit & Drinks",serving:"1 oz",calories:140,protein:2,carbs:18,fat:6,description:"Kid-sized chips portion",badges:["Kids"] },
  { id:"chip-kids-mandarins",restaurantId:"chipotle",name:"Kid's Mandarins",category:"Kids Fruit & Drinks",serving:"1 side",calories:35,protein:1,carbs:9,fat:0,description:"Mandarin side for kids meals",badges:["Kids","Low Calorie"] },
  { id:"chip-kids-blueberries",restaurantId:"chipotle",name:"Kid's Blueberries",category:"Kids Fruit & Drinks",serving:"1 side",calories:20,protein:1,carbs:5,fat:0,description:"Blueberry side for kids meals",badges:["Kids","Low Calorie"] },
  { id:"chip-kids-juice",restaurantId:"chipotle",name:"Organic Apple Juice",category:"Kids Drinks",serving:"1 kids drink",calories:100,protein:0,carbs:24,fat:0,description:"Kids organic juice drink",badges:["Kids"] },
  { id:"chip-kids-milk",restaurantId:"chipotle",name:"Organic Milk",category:"Kids Drinks",serving:"1 kids drink",calories:110,protein:8,carbs:12,fat:2.5,description:"Kids organic milk drink",badges:["Kids"] },
  { id:"cfa-nuggets",restaurantId:"chickfila",name:"Grilled Nuggets",category:"Entrees",serving:"12 count",calories:200,protein:38,carbs:2,fat:4.5,description:"Bite-sized grilled chicken breast",badges:["High Protein","Low Carb"] },
  { id:"cfa-sandwich",restaurantId:"chickfila",name:"Chick-fil-A Chicken Sandwich",category:"Entrees",serving:"1 sandwich",calories:420,protein:29,carbs:41,fat:18,description:"Breaded chicken breast on a toasted bun",badges:["Popular"] },
  { id:"cfa-fries",restaurantId:"chickfila",name:"Waffle Potato Fries",category:"Sides",serving:"Medium",calories:420,protein:5,carbs:45,fat:24,description:"Crispy waffle-cut potato fries",badges:["Popular"] },
  { id:"cfa-fruit",restaurantId:"chickfila",name:"Fruit Cup",category:"Sides",serving:"Medium",calories:70,protein:1,carbs:16,fat:0,description:"Fresh seasonal fruit",badges:["Low Calorie"] },
  { id:"cfa-sauce",restaurantId:"chickfila",name:"Chick-fil-A Sauce",category:"Sauces",serving:"1 packet",calories:140,protein:0,carbs:7,fat:13,description:"Signature dipping sauce",badges:[] },
  { id:"cfa-bbq",restaurantId:"chickfila",name:"Zesty Buffalo Sauce",category:"Sauces",serving:"1 packet",calories:25,protein:0,carbs:1,fat:2.5,description:"Tangy buffalo dipping sauce",badges:["Low Calorie"] },
  { id:"cfa-tea",restaurantId:"chickfila",name:"Unsweetened Iced Tea",category:"Drinks",serving:"Medium",calories:0,protein:0,carbs:0,fat:0,description:"Fresh-brewed iced tea",badges:["Low Calorie"] },
  { id:"pot-turkey",restaurantId:"potbelly",name:"Turkey Breast",category:"Sandwiches",serving:"Original sandwich",calories:443,protein:34,carbs:53,fat:11,description:"Turkey breast with Swiss cheese",badges:["High Protein"] },
  { id:"pot-wreck",restaurantId:"potbelly",name:"A Wreck",category:"Sandwiches",serving:"Original sandwich",calories:646,protein:37,carbs:55,fat:31,description:"Salami, roast beef, turkey and ham",badges:["Popular"] },
  { id:"pot-white",restaurantId:"potbelly",name:"Original White Bread",category:"Bread",serving:"Original roll",calories:310,protein:12,carbs:62,fat:3,description:"Toasted white sandwich roll",badges:[] },
  { id:"pot-multigrain",restaurantId:"potbelly",name:"Original Multigrain Bread",category:"Bread",serving:"Original roll",calories:310,protein:13,carbs:62,fat:3.5,description:"Toasted multigrain sandwich roll",badges:[] },
  { id:"pot-turkey-meat",restaurantId:"potbelly",name:"Turkey Breast",category:"Meats",serving:"1 portion",calories:70,protein:14,carbs:1,fat:1,description:"Sliced turkey breast",badges:["High Protein"] },
  { id:"pot-ham",restaurantId:"potbelly",name:"Smoked Ham",category:"Meats",serving:"1 portion",calories:70,protein:11,carbs:2,fat:2,description:"Sliced smoked ham",badges:[] },
  { id:"pot-roastbeef",restaurantId:"potbelly",name:"Roast Beef",category:"Meats",serving:"1 portion",calories:90,protein:16,carbs:0,fat:3,description:"Sliced roast beef",badges:["High Protein"] },
  { id:"pot-bacon",restaurantId:"potbelly",name:"Bacon",category:"Meats",serving:"1 portion",calories:80,protein:6,carbs:0,fat:6,description:"Crispy bacon strips",badges:["Low Carb"] },
  { id:"pot-swiss",restaurantId:"potbelly",name:"Swiss Cheese",category:"Cheese",serving:"1 portion",calories:100,protein:7,carbs:1,fat:8,description:"Melted Swiss cheese",badges:[] },
  { id:"pot-avocado",restaurantId:"potbelly",name:"Avocado",category:"Toppings",serving:"1 serving",calories:117,protein:1,carbs:6,fat:11,description:"Fresh sliced avocado",badges:[] },
  { id:"pot-hotpeppers",restaurantId:"potbelly",name:"Hot Peppers",category:"Toppings",serving:"1 serving",calories:25,protein:0,carbs:4,fat:0,description:"Signature spicy peppers",badges:["Low Calorie"] },
  { id:"pot-lettuce",restaurantId:"potbelly",name:"Lettuce",category:"Toppings",serving:"1 serving",calories:5,protein:0,carbs:1,fat:0,description:"Crisp shredded lettuce",badges:["Low Calorie"] },
  { id:"pot-tomato",restaurantId:"potbelly",name:"Tomato",category:"Toppings",serving:"1 serving",calories:5,protein:0,carbs:1,fat:0,description:"Fresh sliced tomato",badges:["Low Calorie"] },
  { id:"pot-mayo",restaurantId:"potbelly",name:"Mayo",category:"Spreads",serving:"1 serving",calories:160,protein:0,carbs:0,fat:18,description:"Creamy mayonnaise",badges:[] },
  { id:"pot-mustard",restaurantId:"potbelly",name:"Deli Mustard",category:"Spreads",serving:"1 serving",calories:20,protein:0,carbs:1,fat:0,description:"Tangy deli mustard",badges:["Low Calorie"] },
  { id:"pot-chips",restaurantId:"potbelly",name:"Zapp's Chips",category:"Sides",serving:"1 bag",calories:220,protein:3,carbs:24,fat:13,description:"Crunchy kettle-style chips",badges:[] },
  { id:"jj-turkey",restaurantId:"jimmyjohns",name:"Turkey Tom",category:"Sandwiches",serving:"8 inch sandwich",calories:480,protein:23,carbs:48,fat:19,description:"Turkey breast, lettuce, tomato and mayo",badges:["Popular"] },
  { id:"jj-unwich",restaurantId:"jimmyjohns",name:"Turkey Tom Unwich",category:"Sandwiches",serving:"Lettuce wrap",calories:250,protein:23,carbs:7,fat:16,description:"Turkey Tom wrapped in lettuce",badges:["Low Carb"] },
  { id:"jj-french",restaurantId:"jimmyjohns",name:"8-inch French Bread",category:"Bread",serving:"1 roll",calories:360,protein:14,carbs:66,fat:2,description:"Classic freshly baked French bread",badges:[] },
  { id:"jj-wheat",restaurantId:"jimmyjohns",name:"Sliced Wheat Bread",category:"Bread",serving:"1 sandwich",calories:290,protein:12,carbs:48,fat:5.5,description:"Hearty sliced wheat bread",badges:[] },
  { id:"jj-lettuce-wrap",restaurantId:"jimmyjohns",name:"Unwich Lettuce Wrap",category:"Bread",serving:"1 wrap",calories:10,protein:1,carbs:2,fat:0,description:"Lettuce wrap instead of bread",badges:["Low Carb"] },
  { id:"jj-extra-turkey",restaurantId:"jimmyjohns",name:"Turkey",category:"Meats",serving:"1 regular portion",calories:60,protein:14,carbs:1,fat:.5,description:"Sliced turkey breast",badges:["High Protein"] },
  { id:"jj-roastbeef",restaurantId:"jimmyjohns",name:"Roast Beef",category:"Meats",serving:"1 regular portion",calories:90,protein:16,carbs:0,fat:3,description:"Sliced roast beef",badges:["High Protein"] },
  { id:"jj-ham",restaurantId:"jimmyjohns",name:"Ham",category:"Meats",serving:"1 regular portion",calories:70,protein:11,carbs:2,fat:1.5,description:"Sliced ham",badges:[] },
  { id:"jj-salami",restaurantId:"jimmyjohns",name:"Salami & Capocollo",category:"Meats",serving:"1 regular portion",calories:160,protein:14,carbs:2,fat:11,description:"Italian salami and capocollo",badges:[] },
  { id:"jj-bacon",restaurantId:"jimmyjohns",name:"Bacon",category:"Meats",serving:"1 regular portion",calories:90,protein:6,carbs:0,fat:7,description:"Crispy bacon",badges:["Low Carb"] },
  { id:"jj-provolone",restaurantId:"jimmyjohns",name:"Provolone Cheese",category:"Cheese",serving:"1 regular portion",calories:120,protein:8,carbs:0,fat:9,description:"Sliced provolone cheese",badges:[] },
  { id:"jj-mayo",restaurantId:"jimmyjohns",name:"Hellmann's Mayo",category:"Spreads",serving:"1 regular portion",calories:160,protein:0,carbs:0,fat:16,description:"Creamy mayonnaise",badges:[] },
  { id:"jj-oil",restaurantId:"jimmyjohns",name:"Oil & Vinegar",category:"Spreads",serving:"1 regular portion",calories:40,protein:0,carbs:0,fat:5,description:"Oil and vinegar blend",badges:[] },
  { id:"jj-peppers",restaurantId:"jimmyjohns",name:"Jimmy Peppers",category:"Toppings",serving:"1 regular portion",calories:0,protein:0,carbs:1,fat:0,description:"Hot cherry peppers",badges:["Low Calorie"] },
  { id:"jj-tomato",restaurantId:"jimmyjohns",name:"Tomato",category:"Toppings",serving:"1 regular portion",calories:10,protein:0,carbs:2,fat:0,description:"Fresh sliced tomato",badges:["Low Calorie"] },
  { id:"jj-lettuce",restaurantId:"jimmyjohns",name:"Lettuce",category:"Toppings",serving:"1 regular portion",calories:5,protein:0,carbs:1,fat:0,description:"Crisp shredded lettuce",badges:["Low Calorie"] },
  { id:"jm-7",restaurantId:"jerseymikes",name:"#7 Turkey and Provolone",category:"Sandwiches",serving:"Regular sub",calories:820,protein:45,carbs:66,fat:41,description:"Turkey, provolone and Mike's Way toppings",badges:["Popular","High Protein"] },
  { id:"jm-white",restaurantId:"jerseymikes",name:"White Sub Roll",category:"Bread",serving:"Regular roll",calories:300,protein:10,carbs:58,fat:3,description:"Fresh-baked white sub roll",badges:[] },
  { id:"jm-wheat",restaurantId:"jerseymikes",name:"Wheat Sub Roll",category:"Bread",serving:"Regular roll",calories:300,protein:11,carbs:57,fat:4,description:"Fresh-baked wheat sub roll",badges:[] },
  { id:"jm-rosemary-parm",restaurantId:"jerseymikes",name:"Rosemary Parmesan Bread",category:"Bread",serving:"Regular roll",calories:320,protein:11,carbs:60,fat:5,description:"Rosemary parmesan sub roll",badges:["Popular"] },
  { id:"jm-tub",restaurantId:"jerseymikes",name:"Sub in a Tub",category:"Bread",serving:"No bread bowl",calories:20,protein:1,carbs:4,fat:0,description:"Lettuce bowl instead of bread",badges:["Low Carb"] },
  { id:"jm-turkey",restaurantId:"jerseymikes",name:"Turkey Breast",category:"Meats",serving:"1 regular portion",calories:120,protein:24,carbs:2,fat:1,description:"Fresh-sliced turkey breast",badges:["High Protein"] },
  { id:"jm-ham",restaurantId:"jerseymikes",name:"Ham",category:"Meats",serving:"1 regular portion",calories:100,protein:18,carbs:2,fat:3,description:"Fresh-sliced ham",badges:["High Protein"] },
  { id:"jm-roastbeef",restaurantId:"jerseymikes",name:"Roast Beef",category:"Meats",serving:"1 regular portion",calories:140,protein:24,carbs:0,fat:5,description:"Fresh-sliced roast beef",badges:["High Protein"] },
  { id:"jm-bacon",restaurantId:"jerseymikes",name:"Bacon",category:"Meats",serving:"1 regular portion",calories:80,protein:6,carbs:0,fat:6,description:"Crispy bacon strips",badges:["Low Carb"] },
  { id:"jm-provolone",restaurantId:"jerseymikes",name:"Provolone",category:"Cheese",serving:"1 regular portion",calories:120,protein:8,carbs:1,fat:9,description:"Sliced provolone cheese",badges:[] },
  { id:"jm-mayo",restaurantId:"jerseymikes",name:"Mayo",category:"Spreads",serving:"1 regular portion",calories:170,protein:0,carbs:0,fat:19,description:"Creamy mayonnaise",badges:[] },
  { id:"jm-oil",restaurantId:"jerseymikes",name:"Olive Oil Blend",category:"Spreads",serving:"1 regular portion",calories:125,protein:0,carbs:0,fat:14,description:"Oil blend used for Mike's Way",badges:[] },
  { id:"jm-vinegar",restaurantId:"jerseymikes",name:"Red Wine Vinegar",category:"Spreads",serving:"1 regular portion",calories:5,protein:0,carbs:1,fat:0,description:"Red wine vinegar",badges:["Low Calorie"] },
  { id:"jm-lettuce",restaurantId:"jerseymikes",name:"Lettuce",category:"Toppings",serving:"1 regular portion",calories:5,protein:0,carbs:1,fat:0,description:"Shredded lettuce",badges:["Low Calorie"] },
  { id:"jm-tomato",restaurantId:"jerseymikes",name:"Tomato",category:"Toppings",serving:"1 regular portion",calories:10,protein:0,carbs:2,fat:0,description:"Fresh sliced tomato",badges:["Low Calorie"] },
  { id:"jm-onion",restaurantId:"jerseymikes",name:"Onion",category:"Toppings",serving:"1 regular portion",calories:10,protein:0,carbs:2,fat:0,description:"Sliced onion",badges:["Low Calorie"] },
  { id:"culvers-grilled",restaurantId:"culvers",name:"Grilled Chicken Sandwich",category:"Entrees",serving:"1 sandwich",calories:480,protein:36,carbs:40,fat:19,description:"Grilled chicken on a toasted bun",badges:["High Protein"] },
  { id:"culvers-burger",restaurantId:"culvers",name:"ButterBurger Cheese",category:"Entrees",serving:"Single burger",calories:460,protein:23,carbs:39,fat:24,description:"Fresh beef with Wisconsin cheese",badges:["Popular"] },
  { id:"culvers-curds",restaurantId:"culvers",name:"Wisconsin Cheese Curds",category:"Sides",serving:"Medium",calories:490,protein:17,carbs:46,fat:27,description:"Fried Wisconsin cheese curds",badges:[] },
  { id:"culvers-broccoli",restaurantId:"culvers",name:"Steamed Broccoli",category:"Sides",serving:"Regular",calories:40,protein:3,carbs:7,fat:0,description:"Tender steamed broccoli",badges:["Low Calorie"] },
  { id:"culvers-custard",restaurantId:"culvers",name:"Vanilla Custard",category:"Desserts",serving:"Dish · 1 scoop",calories:310,protein:6,carbs:31,fat:19,description:"Fresh frozen custard",badges:[] },
  { id:"star-coldbrew",restaurantId:"starbucks",name:"Cold Brew Coffee",category:"Drinks",serving:"Grande",calories:5,protein:0,carbs:0,fat:0,description:"Slow-steeped cold brew over ice",badges:["Low Calorie"] },
  { id:"star-latte",restaurantId:"starbucks",name:"Caffe Latte",category:"Drinks",serving:"Grande with 2% milk",calories:190,protein:13,carbs:18,fat:7,description:"Espresso with steamed milk",badges:["High Protein"] },
  { id:"star-americano",restaurantId:"starbucks",name:"Caffe Americano",category:"Drinks",serving:"Grande",calories:15,protein:1,carbs:2,fat:0,description:"Espresso shots with hot water",badges:["Low Calorie"] },
  { id:"star-iced-coffee",restaurantId:"starbucks",name:"Iced Coffee",category:"Drinks",serving:"Grande, unsweetened",calories:5,protein:0,carbs:0,fat:0,description:"Freshly brewed iced coffee",badges:["Low Calorie"] },
  { id:"star-vsc-coldbrew",restaurantId:"starbucks",name:"Vanilla Sweet Cream Cold Brew",category:"Drinks",serving:"Grande",calories:110,protein:1,carbs:14,fat:5,description:"Cold brew with vanilla sweet cream",badges:[] },
  { id:"star-caramel-macchiato",restaurantId:"starbucks",name:"Caramel Macchiato",category:"Drinks",serving:"Grande with 2% milk",calories:250,protein:10,carbs:35,fat:7,description:"Vanilla, steamed milk, espresso and caramel drizzle",badges:[] },
  { id:"star-pink-drink",restaurantId:"starbucks",name:"Pink Drink",category:"Drinks",serving:"Grande",calories:140,protein:1,carbs:28,fat:2.5,description:"Strawberry acai with coconutmilk",badges:[] },
  { id:"star-matcha",restaurantId:"starbucks",name:"Iced Matcha Tea Latte",category:"Drinks",serving:"Grande with 2% milk",calories:200,protein:12,carbs:29,fat:5,description:"Matcha green tea with milk over ice",badges:[] },
  { id:"star-mocha",restaurantId:"starbucks",name:"Caffe Mocha",category:"Drinks",serving:"Grande with 2% milk",calories:370,protein:14,carbs:43,fat:15,description:"Espresso, mocha sauce, steamed milk and whipped cream",badges:[] },
  { id:"star-frap",restaurantId:"starbucks",name:"Caramel Frappuccino",category:"Drinks",serving:"Grande",calories:380,protein:4,carbs:55,fat:16,description:"Coffee, caramel syrup, milk and ice",badges:[] },
  { id:"star-oatmilk",restaurantId:"starbucks",name:"Oatmilk",category:"Customizations",serving:"Grande substitution",calories:70,protein:1,carbs:12,fat:3,description:"Creamy oatmilk substitution",badges:[] },
  { id:"star-syrup",restaurantId:"starbucks",name:"Vanilla Syrup",category:"Customizations",serving:"1 pump",calories:20,protein:0,carbs:5,fat:0,description:"One pump of vanilla syrup",badges:[] },
  { id:"star-cold-foam",restaurantId:"starbucks",name:"Vanilla Sweet Cream Cold Foam",category:"Customizations",serving:"1 topping",calories:110,protein:1,carbs:14,fat:5,description:"Cold foam topping",badges:[] },
  { id:"star-espresso-shot",restaurantId:"starbucks",name:"Espresso Shot",category:"Customizations",serving:"1 shot",calories:5,protein:0,carbs:1,fat:0,description:"Add an espresso shot",badges:["Low Calorie"] },
  { id:"star-egg",restaurantId:"starbucks",name:"Egg White & Roasted Red Pepper Bites",category:"Food",serving:"2 bites",calories:170,protein:12,carbs:11,fat:8,description:"Sous vide egg white bites",badges:["High Protein"] },
  { id:"star-spinach-wrap",restaurantId:"starbucks",name:"Spinach, Feta & Egg White Wrap",category:"Food",serving:"1 wrap",calories:290,protein:20,carbs:34,fat:8,description:"Egg white wrap with spinach and feta",badges:["High Protein"] },
  { id:"star-turkey-bacon",restaurantId:"starbucks",name:"Turkey Bacon, Cheddar & Egg White Sandwich",category:"Food",serving:"1 sandwich",calories:230,protein:17,carbs:28,fat:5,description:"Breakfast sandwich with turkey bacon",badges:["High Protein"] },
  { id:"star-bacon-gouda",restaurantId:"starbucks",name:"Bacon, Gouda & Egg Sandwich",category:"Food",serving:"1 sandwich",calories:360,protein:19,carbs:35,fat:18,description:"Breakfast sandwich with bacon and Gouda",badges:["High Protein"] },
  { id:"mcd-bigmac",restaurantId:"mcdonalds",name:"Big Mac",category:"Entrees",serving:"1 burger",calories:590,protein:25,carbs:46,fat:34,description:"Two beef patties, Big Mac sauce, lettuce, cheese, pickles and onions",badges:["Popular"] },
  { id:"mcd-quarter",restaurantId:"mcdonalds",name:"Quarter Pounder with Cheese",category:"Entrees",serving:"1 burger",calories:520,protein:30,carbs:42,fat:26,description:"Quarter pound beef patty with cheese",badges:["High Protein"] },
  { id:"mcd-mccrispy",restaurantId:"mcdonalds",name:"McCrispy",category:"Entrees",serving:"1 sandwich",calories:470,protein:26,carbs:45,fat:20,description:"Crispy chicken sandwich",badges:["High Protein"] },
  { id:"mcd-nuggets",restaurantId:"mcdonalds",name:"Chicken McNuggets",category:"Entrees",serving:"10 piece",calories:410,protein:23,carbs:26,fat:24,description:"Ten piece Chicken McNuggets",badges:["Popular"] },
  { id:"mcd-egg-mcmuffin",restaurantId:"mcdonalds",name:"Egg McMuffin",category:"Breakfast",serving:"1 sandwich",calories:310,protein:17,carbs:30,fat:13,description:"Egg, Canadian bacon and cheese on an English muffin",badges:["High Protein"] },
  { id:"mcd-fries",restaurantId:"mcdonalds",name:"World Famous Fries",category:"Sides",serving:"Medium",calories:320,protein:5,carbs:43,fat:15,description:"Medium french fries",badges:["Popular"],control:"size" },
  { id:"mcd-apple-slices",restaurantId:"mcdonalds",name:"Apple Slices",category:"Sides",serving:"1 pack",calories:15,protein:0,carbs:4,fat:0,description:"Apple slices side",badges:["Low Calorie"] },
  { id:"mcd-coke",restaurantId:"mcdonalds",name:"Coca-Cola",category:"Drinks",serving:"Medium",calories:210,protein:0,carbs:58,fat:0,description:"Medium fountain Coca-Cola",badges:[],control:"size" },
  { id:"mcd-diet-coke",restaurantId:"mcdonalds",name:"Diet Coke",category:"Drinks",serving:"Medium",calories:0,protein:0,carbs:0,fat:0,description:"Medium fountain Diet Coke",badges:["Low Calorie"],control:"size" },
  { id:"mcd-iced-coffee",restaurantId:"mcdonalds",name:"Iced Coffee",category:"Drinks",serving:"Medium",calories:180,protein:2,carbs:28,fat:7,description:"Medium vanilla iced coffee",badges:[],control:"size" },
  { id:"mcd-bbq",restaurantId:"mcdonalds",name:"Tangy BBQ Sauce",category:"Sauces",serving:"1 packet",calories:45,protein:0,carbs:11,fat:0,description:"BBQ dipping sauce",badges:[] },
  { id:"mcd-ranch",restaurantId:"mcdonalds",name:"Creamy Ranch Sauce",category:"Sauces",serving:"1 packet",calories:110,protein:0,carbs:1,fat:12,description:"Ranch dipping sauce",badges:[] },
  { id:"tb-burrito",restaurantId:"tacobell",name:"Bean Burrito",category:"Entrees",serving:"1 burrito",calories:360,protein:13,carbs:54,fat:9,description:"Beans, red sauce, onions and cheese",badges:[] },
  { id:"tb-taco",restaurantId:"tacobell",name:"Crunchy Taco",category:"Entrees",serving:"1 taco",calories:170,protein:8,carbs:13,fat:10,description:"Seasoned beef, lettuce and cheese",badges:["Popular"] },
  { id:"tb-beef",restaurantId:"tacobell",name:"Extra Seasoned Beef",category:"Extras",serving:"1 serving",calories:70,protein:5,carbs:1,fat:4.5,description:"Add seasoned beef",badges:["High Protein"] },
  { id:"tb-potatoes",restaurantId:"tacobell",name:"Seasoned Potatoes",category:"Extras",serving:"1 serving",calories:120,protein:2,carbs:20,fat:4,description:"Crispy seasoned potato bites",badges:[] },
  { id:"tb-sauce",restaurantId:"tacobell",name:"Creamy Jalapeno Sauce",category:"Sauces",serving:"1 serving",calories:80,protein:0,carbs:1,fat:8,description:"Creamy jalapeno sauce",badges:[] },
];

export const macroTotal = (items: { item: MenuItem; quantity: number }[]) =>
  items.reduce((sum, { item, quantity }) => ({
    calories: sum.calories + item.calories * quantity,
    protein: sum.protein + item.protein * quantity,
    carbs: sum.carbs + item.carbs * quantity,
    fat: sum.fat + item.fat * quantity,
  }), { calories: 0, protein: 0, carbs: 0, fat: 0 });
